Question 1 – Student Marks Array


The marks obtained by five students in a subject are given as [78, 65, 89, 56, 92].


 Create a NumPy array and display the array along with its basic properties.

In [2]:
import numpy as np
marks=np.array([78,65,89,56,92])

print("Array:", marks)
print("Dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Array: [78 65 89 56 92]
Dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


Question 2 – Student Marks Access


The marks of five students are stored in a NumPy array as [72, 85, 64, 90, 76].

 Write a program to access and display specific student marks using NumPy indexing and slicing.


In [5]:
marks=np.array([72,85,64,90,76])
for i in range(len(marks)):
  print(f"Student {i+1} Marks: {marks[i]}")

print("Marks of students 2 to 4: ", marks[1:4])

Student 1 Marks: 72
Student 2 Marks: 85
Student 3 Marks: 64
Student 4 Marks: 90
Student 5 Marks: 76
Marks of students 2 to 4:  [85 64 90]


Question 3 – Subject-wise Marks


The marks obtained by five students in three subjects are given below.

Create a NumPy array to represent the data and reshape it into an appropriate matrix format.

[78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92]


In [6]:
marks = np.array([78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92])
marks=marks.reshape(5,3)
print(marks)

[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


Question 4 – Internal and External Marks


The internal and external examination marks of five students are stored in two NumPy arrays.

Write a program to calculate the final marks of each student using NumPy array operations.


In [7]:
internal=np.array([25,38,42,30,41])
external=np.array([45,30,40,45,44])
final_marks=internal+external
print("Final Marks: ",final_marks)

Final Marks:  [70 68 82 75 85]


Question 5 – Pass Percentage Analysis


The marks obtained by five students are [45, 78, 56, 32, 91].

Using NumPy Boolean masking, identify the students who have secured 50 marks or above.


In [11]:
marks=np.array([45,78,56,32,91])
passed=marks[marks>50]
print(f"STudents who secured above 50 : {passed}")
sts=np.arange(1,6)
print(sts[marks>50])

STudents who secured above 50 : [78 56 91]
[2 3 5]


Question 6 – Average Marks

The marks of five students in three subjects are represented using a NumPy matrix.

Write a program to calculate the average marks of each student.


In [14]:
marks=np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

avg=np.mean(marks,axis=1)
print(f"Average marks of Students: {avg}")

Average marks of Students: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


Question 7 – Class Performance Statistics

The marks obtained by five students are [67, 82, 91, 74, 58].

Using NumPy statistical functions, determine the total, average, highest, lowest, and standard deviation of the marks.


In [15]:
marks=np.array([67,82,91,74,58])
total=np.sum(marks)
avg=np.mean(marks)
highest=np.max(marks)
lowest=np.min(marks)
std=np.std(marks)

print("Total marks: ", total)
print("Average: ",avg)
print("Highest: ",highest)
print("Lowest: ",lowest)
print("Standard deviation: ",std)

Total marks:  372
Average:  74.4
Highest:  91
Lowest:  58
Standard deviation:  11.46472851837321


Question 8 – Subject-wise Performance

The marks of five students in three subjects are stored in a NumPy matrix.

Write a program to calculate the total marks obtained in each subject using an appropriate axis operation.


In [16]:
marks=np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

total=np.sum(marks,axis=0)
print(total)

[382 399 416]


Question 9 – Student-wise Performance

The marks of five students in three subjects are stored in a NumPy matrix.

Write a program to calculate the total marks obtained by each student using an appropriate axis operation.


In [18]:
marks=np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
total=np.sum(marks,axis=1)
print(total)

[253 217 263 188 276]


Question 10 – Student Ranking

The total marks obtained by five students are [245, 278, 219, 290, 256].

 Use NumPy sorting and indexing operations to arrange the marks in order and determine the ranking of the students.


In [22]:
total_marks=[245, 278, 219, 290, 256]
ranking=np.sort(total_marks)[::-1]
for i in range(len(total_marks)):
  print(f"Rank {i+1}: {ranking[i]}")



Rank 1: 290
Rank 2: 278
Rank 3: 256
Rank 4: 245
Rank 5: 219


Question 11 – Duplicate Marks Analysis

The marks obtained by five students are [85, 92, 85, 76, 92].

Use NumPy functions to identify the unique marks obtained by the students.


In [23]:
marks=np.array([85,92,85,76,92])
uniq=np.unique(marks)
print(uniq)

[76 85 92]


Question 12 – Missing Marks

The marks of five students are represented as [78, 85, np.nan, 92, 67], where np.nan represents a missing mark.

 Write a NumPy program to calculate the average marks without considering the missing value.


In [24]:
marks=np.array([78, 85, np.nan, 92, 67])
average=np.nanmean(marks)
print("Average marks:",average)

Average marks: 80.5


Question 13 – Grade Classification

The marks obtained by five students are [95, 82, 74, 61, 45].

Using NumPy conditional operations, classify the students into appropriate grade categories based on their marks.


In [25]:
marks=np.array([95,82,74,61,45])
grades = np.where(marks >= 90, 'A',
         np.where(marks >= 80, 'B',
         np.where(marks >= 70, 'C',
         np.where(marks >= 60, 'D', 'F'))))

print(grades)

['A' 'B' 'C' 'D' 'F']


Question 14 – Random Marks Generation

Generate marks for five students using NumPy's random number generation functionality.

Perform basic statistical analysis on the generated marks


In [28]:
marks = np.random.randint(0,101,5)

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Marks: [31 27 92 87 67]
Total: 304
Average: 60.8
Highest: 92
Lowest: 27
Standard deviation: 27.308606701917256


Question 15 – Student Performance Analysis

The marks of five students in three subjects are stored in a NumPy array.

Develop a program to perform a complete student performance analysis by calculating the total marks, average marks, highest marks, lowest marks, and identifying students who perform above the class average.


In [29]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)

class_average = np.mean(average)

print("Total:", total)
print("Average:", average)
print("Highest:", highest)
print("Lowest:", lowest)
print("Class average:", class_average)

above_average = np.where(average > class_average)[0]

print("Students above class average:", above_average + 1)

Total: [253 217 263 188 276]
Average: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest: [90 80 91 70 95]
Lowest: [78 65 84 56 89]
Class average: 79.8
Students above class average: [1 3 5]
